
trigger:
  tags:
    include:
    - '*'
  branches:
   include:
     - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- bash: |
    tags=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
    echo "Latest tag on main branch: $tags"
    echo "##vso[task.setvariable variable=myVersion;isOutput=true]$(tags)"
  name: createTagVariableStep
  displayName: 'Get Latest Tag on Main Branch'

- script: echo "The version is $(createTagVariableStep.myVersion)"
  displayName: 'Display Version'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '/p:Version=$(tags)'

- bash: | 
    ls
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'


