
trigger:
  tags:
    include:
    - '*'
  branches:
   include:
     - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- bash: |
    latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
    echo "Latest tag on main branch: $latest_tag"
    echo "##vso[task.setvariable variable=tag;isOutput=true]$latest_tag"
  displayName: 'Get Latest Tag on Main Branch'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '/p:Version=$(Tag)'

- bash: | 
    ls
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'


