
trigger:
  tags:
    include:
    - '*'
  branches:
   include:
     - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- bash: |
    tags=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
    echo "Latest tag on main branch: $tags"
    echo "##vso[task.setvariable variable=myVersion;isOutput=true]$tags"
  name: createTagVariableStep
  displayName: 'Get Latest Tag on Main Branch'

- script: |
    choco install dotnet4.5
  displayName: 'Install .NET Framework 4.5'

- script: echo "The version is $(createTagVariableStep.myVersion)"
  displayName: 'Display Version'
  
- bash: | 
    ls
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '/src/*.csproj'
    arguments: '/p:Version=$(createTagVariableStep.myVersion)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'


