
trigger:
  tags:
    include:
    - '*'
  branches:
   include:
     - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- bash: |
    latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
    echo "Latest tag on main branch: $latest_tag"
  displayName: 'Get Latest Tag on Main Branch'
- task: VSBuild@1
  inputs:
    solution: MyLib.sln
    platform: Any CPU
    configuration: Release
    msbuildArgs: /p:Version=$(Build.BuildNumber)
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'


